name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    continue-on-error: ${{ matrix.env.PRERELEASE }}
    strategy:
      fail-fast: false
      matrix:
        env:
          - {ROS_DISTRO: kinetic, ROS_REPO: ros, ABICHECK_URL: "github:ros-drivers/openni2_camera#ros1", ABICHECK_MERGE: false, PRERELEASE: false}
          - {ROS_DISTRO: melodic, ROS_REPO: ros, ABICHECK_URL: "github:ros-drivers/openni2_camera#ros1", ABICHECK_MERGE: false, PRERELEASE: false}
          - {ROS_DISTRO: noetic, ROS_REPO: ros, ABICHECK_URL: "github:ros-drivers/openni2_camera#ros1", ABICHECK_MERGE: false, PRERELEASE: false}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
